/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/moments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Published moments
         * @description Every published moment, with who governed, the length of its story and its cast.
         */
        get: operations["listMoments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A moment
         * @description The world around a moment, its eras, people, everyday lives, events and doors.
         */
        get: operations["getMoment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moments/{id}/story": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A moment's story
         * @description The story cards of a moment, in order, and its doors to other moments.
         */
        get: operations["getStory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A person in a year
         * @description A person in the world around them in a year, with their life in their time. Without a year, or with a year
         *     outside their life, the page looks at their prime.
         */
        get: operations["getPerson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/years/{year}/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * People alive elsewhere in a year
         * @description A few people alive in a year in each region but one, preferring those in the middle of their lives.
         */
        get: operations["listAliveElsewhere"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search people and moments
         * @description Accent-insensitive, so `zola` finds Émile Zola. Fewer than two characters find nothing.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regions */
        get: operations["listRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eras */
        get: operations["listEras"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An era
         * @description An era with the people alive in it by domain, its events and the moments set in it.
         */
        get: operations["getEra"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Count a visitor event
         * @description Counts one anonymous event from the browser. Nothing identifies the visitor: no address, user agent, cookie
         *     or id is read or kept. Every value must come from a fixed vocabulary. `navigator.sendBeacon` sends
         *     `text/plain`, so that is accepted too.
         */
        post: operations["recordEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description An error, as RFC 9457 Problem Details. */
        ProblemDetail: {
            /**
             * @description A URI that identifies the kind of problem; `about:blank` when the status says it all.
             * @default about:blank
             */
            type: string;
            /** @description The status's reason phrase, e.g. "Not Found". */
            title?: string;
            /** Format: int32 */
            status?: number;
            /** @description What went wrong with this request, e.g. "Unknown moment: atlantis". */
            detail?: string;
            /** @description The path that was requested. */
            instance?: string;
        };
        /**
         * @description What a person is known for.
         * @enum {string}
         */
        Domain: "POWER" | "ARTS" | "EVERYDAY";
        /** @description A place, seen through today's borders. */
        Region: {
            /** @example FR */
            code: string;
            /** @example France */
            name: string;
        };
        /** @description A public-domain image with its credit and the page it comes from. */
        Artwork: {
            url: string;
            credit: string;
            sourceUrl: string;
        };
        /** @description The world around a moment, one line per domain, and what is happening elsewhere at the same time. */
        WorldAround: {
            governs: string;
            everyday: string;
            arts: string;
            meanwhile: string;
        };
        /** @description A region at a time span, named after who governed it. Both years are inclusive. */
        Era: {
            id: string;
            label: string;
            regionCode: string;
            region: string;
            governedBy: string;
            /** Format: int32 */
            startYear: number;
            /** Format: int32 */
            endYear: number;
        };
        Person: {
            slug: string;
            name: string;
            /** Format: int32 */
            birthYear: number;
            /** Format: int32 */
            deathYear: number | null;
            /** @description True when the birth or death year is only known approximately. */
            datesApproximate: boolean;
            regionCode: string;
            region: string;
            domain: components["schemas"]["Domain"];
            occupation: string;
            /** @description One or two sentences, hand-written or the lead of the Wikipedia article. */
            bioShort: string | null;
            portraitUrl: string | null;
        };
        /** @description A typical existence in an era, shown as representative of the period rather than as a real person. Drawn with its art, else its icon, else a generic one. */
        Life: {
            id: string;
            label: string;
            description: string;
            /** Format: int32 */
            startYear: number;
            /** Format: int32 */
            endYear: number;
            art: components["schemas"]["LifeArt"] | null;
            icon: (string & components["schemas"]["LifeIcon"]) | null;
        };
        /** @description A public-domain image of a typical life, with its credit, the page it comes from, and how to frame it in a circle. */
        LifeArt: {
            url: string;
            credit: string;
            sourceUrl: string;
            /**
             * @description The point kept in view when cropping, as CSS `object-position`.
             * @example 50% 70%
             */
            position: string;
            fit: components["schemas"]["ArtFit"];
        };
        /**
         * @description How an image fills its frame, as CSS `object-fit`, `COVER` cropped to fill it, `CONTAIN` whole with a margin.
         * @enum {string}
         */
        ArtFit: "COVER" | "CONTAIN";
        /**
         * @description An icon for a typical life without an image, after the work it stands for.
         * @enum {string}
         */
        LifeIcon: "AMPHORA" | "BRIEFCASE" | "CAR" | "COINS" | "CONCIERGE_BELL" | "FACTORY" | "FISH" | "HAMMER" | "LEAF" | "PICKAXE" | "SHELL" | "SHIELD" | "SHIRT" | "SHOVEL" | "SPOOL" | "SPROUT" | "WHEAT";
        /** @description Someone in an event, with their part in it, e.g. "author". */
        Participant: {
            person: components["schemas"]["Person"];
            role: string;
        };
        /** @description A dated, sourced event. */
        Event: {
            id: string;
            title: string;
            /** Format: int32 */
            year: number;
            description: string;
            sourceUrl: string;
            participants: components["schemas"]["Participant"][];
        };
        EraDetail: {
            era: components["schemas"]["Era"];
            /** @description The people alive in the era, by domain (`POWER`, `ARTS`, `EVERYDAY`). Empty domains are left out. */
            people: {
                [key: string]: components["schemas"]["Person"][];
            };
            events: components["schemas"]["Event"][];
            /** @description The moments set under this regime, to step into. */
            moments: components["schemas"]["MomentSummary"][];
        };
        /** @description What a moment shows on a card, enough to choose it, not to explore it. */
        MomentSummary: {
            id: string;
            regionCode: string;
            region: string;
            /** @example Paris */
            place: string;
            /** @example 1870s */
            period: string;
            /** Format: int32 */
            startYear: number;
            /** Format: int32 */
            endYear: number;
            /**
             * Format: int32
             * @description The year the moment opens on.
             */
            focusYear: number;
            hook: string;
            art: components["schemas"]["Artwork"] | null;
            /** @description Who governed the place in the focus year. */
            governedBy: string | null;
            /**
             * Format: int32
             * @description Number of cards in the story; 0 when no story is written yet.
             */
            storyCards: number;
            /** @description The people the story features. */
            cast: components["schemas"]["Person"][];
            /** @description Shown first on the start page. */
            featured: boolean;
        };
        /** @description A way out of a story into another moment, e.g. "Meanwhile, elsewhere". */
        Door: {
            kind: string;
            text: string;
            target: components["schemas"]["MomentSummary"];
            /** @description People to show on the door, when it follows someone. */
            faces: components["schemas"]["Person"][];
        };
        /** @description Everything the moment page needs; scrubbing through its years happens in the browser. */
        MomentDetail: {
            moment: components["schemas"]["MomentSummary"];
            world: components["schemas"]["WorldAround"] | null;
            eras: components["schemas"]["Era"][];
            people: components["schemas"]["Person"][];
            lives: components["schemas"]["Life"][];
            events: components["schemas"]["Event"][];
            doors: components["schemas"]["Door"][];
        };
        /** @enum {string} */
        CardType: "SCENE" | "PERSON" | "LIFE" | "EVENT";
        /** @description One screen of a moment's story. Person, life and event cards carry the record they are about. */
        StoryCard: {
            type: components["schemas"]["CardType"];
            kicker: string | null;
            title: string | null;
            text: string | null;
            /**
             * Format: int32
             * @description The year the card is set in, used for ages.
             */
            year: number | null;
            person: components["schemas"]["Person"] | null;
            life: components["schemas"]["Life"] | null;
            event: components["schemas"]["Event"] | null;
            /** @description Replaces the moment's artwork while this card is shown. */
            art: components["schemas"]["Artwork"] | null;
        };
        Story: {
            moment: components["schemas"]["MomentSummary"];
            cards: components["schemas"]["StoryCard"][];
            doors: components["schemas"]["Door"][];
        };
        /** @enum {string} */
        LifeLineKind: "BIRTH" | "ERA" | "EVENT" | "OWN_EVENT" | "DEATH";
        /** @description One line of "their life in their time", a dated change around them, with their age. */
        LifeLine: {
            /** Format: int32 */
            year: number;
            /** Format: int32 */
            age: number | null;
            kind: components["schemas"]["LifeLineKind"];
            text: string;
            role: string | null;
        };
        /** @description Someone a person was linked to, how (a pair like "tea master and lord", or their role in a shared event), when, and the source. */
        Connection: {
            person: components["schemas"]["Person"];
            kind: string;
            /** Format: int32 */
            year: number;
            text: string;
            sourceUrl: string;
        };
        PersonDetail: {
            person: components["schemas"]["Person"];
            /** @description The first paragraph of the Wikipedia article. */
            about: string | null;
            wikipediaUrl: string | null;
            /**
             * Format: int32
             * @description The year the rest of the page looks at, the one asked for if they were alive then, else their prime.
             */
            year: number;
            /** Format: int32 */
            age: number;
            world: components["schemas"]["WorldAround"] | null;
            worldMoment: components["schemas"]["MomentSummary"] | null;
            lifeline: components["schemas"]["LifeLine"][];
            /** @description Sourced links to other people, curated ones first, then shared documented events. */
            connections: components["schemas"]["Connection"][];
            aroundPeople: components["schemas"]["Person"][];
            aroundLives: components["schemas"]["Life"][];
            elsewhere: components["schemas"]["Person"][];
            moments: components["schemas"]["MomentSummary"][];
        };
        SearchResults: {
            people: components["schemas"]["Person"][];
            moments: components["schemas"]["MomentSummary"][];
        };
        /** @description One anonymous event. Which fields count depends on `name`; the others are ignored. */
        VisitorEvent: {
            /** @enum {string} */
            name: "page_view" | "story_started" | "story_card_reached" | "story_completed" | "person_panel_opened" | "person_full_page_opened" | "search_used" | "search_result_opened";
            /**
             * @description page_view, the page by template, never a URL.
             * @enum {string}
             */
            page?: "home" | "moment" | "story" | "person";
            /** @description A published moment's id, for page views of a moment or its story, and for story events. */
            moment?: string;
            /**
             * Format: int32
             * @description story_card_reached, the 1-based card.
             */
            card?: number;
            /**
             * @description person_panel_opened and person_full_page_opened, where the visitor came from.
             * @enum {string}
             */
            source?: "home" | "moment" | "story" | "person" | "search" | "panel" | "direct" | "external";
            /**
             * @description search_result_opened, what was picked.
             * @enum {string}
             */
            kind?: "person" | "moment";
        };
    };
    responses: {
        /** @description No such record, or not published. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description A parameter is missing, of the wrong type, or outside its constraints. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        /** @description The moment's id, e.g. `paris-1870s`. */
        MomentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMoments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The published moments, by focus year. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomentSummary"][];
                };
            };
        };
    };
    getMoment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The moment's id, e.g. `paris-1870s`. */
                id: components["parameters"]["MomentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The moment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomentDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The moment's id, e.g. `paris-1870s`. */
                id: components["parameters"]["MomentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The story. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPerson: {
        parameters: {
            query?: {
                /** @description The year to look at them in. */
                year?: number;
            };
            header?: never;
            path: {
                /** @description The person's slug, e.g. `emile-zola`. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The person. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listAliveElsewhere: {
        parameters: {
            query: {
                /** @description The code of the region to leave out, e.g. `FR`. */
                exclude: string;
                /** @description How many people per region. */
                perRegion?: number;
            };
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The people, by region. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    search: {
        parameters: {
            query: {
                /** @description What to look for. Under two characters, once trimmed, it finds nothing. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Names that start with the query first, then by birth. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The regions, by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"][];
                };
            };
        };
    };
    listEras: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every era, by start year. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Era"][];
                };
            };
        };
    };
    getEra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The era's id, e.g. `fr-third-republic`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The era. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EraDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    recordEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitorEvent"];
                "text/plain": string;
            };
        };
        responses: {
            /** @description Counted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not JSON, or a name or value outside the vocabularies. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Larger than 1 KB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
